apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openshift-gitops
resources:
- argocd-cm.yaml
- argocd-cmd-params-cm.yaml
- argocd-gpg-keys-cm.yaml
- argocd-rbac-cm.yaml
- argocd-secret.yaml
- argocd-ssh-know-hosts-cm.yaml
- argocd-tls-certs-cm.yaml
